midexamplana/urls.py
from django.contrib import admin
from django.urls import path, include
from votes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls'))
]

votes/urls.py
from django.urls import path
from . import views

app_name="votes"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('createposition/', views.createposition, name='createposition'),
    path('<int:candidate_id>/', views.detail, name='detail'),
    path('<int:candidate_id>/update', views.update, name ='update'),
]

votes/models.py
from django.db import models
from datetime import datetime
from django.utils.timezone import now
# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300)


class Candidate(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    position = models.CharField(max_length=100, default="none")
    birthdate = models.DateTimeField(default=now)
    platform =  models.TextField(max_length=300)

    def __str__(self):
        return self.firstname

class Vote(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    vote_datetime = models.DateTimeField(default=now)

votes/forms.py
from django.forms import ModelForm
from .models import Candidate,Position

class PostForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']
        exclude = ['position']
class PositionForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']

votes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Candidate, Position
from .forms import PostForm, PositionForm
from datetime import datetime
# Create your views here.

def index(request):
    context = {}
    candidate_names = Candidate.objects.all()
    context['candidate_names']=candidate_names
    return render(request, "index.html", context)

def detail(request, candidate_id):
    context = {}
    context['votes'] = Candidate.objects.get(id=candidate_id)
    return render(request, 'detail.html', context)

def create(request):
    context = {}
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
        else:
            context['form'] = form
            return render(request, 'create.html', context)
    else:
        context['form'] = PostForm(initial={'birthdate': datetime.now().date()})
        return render(request, 'create.html', context)

def createposition(request):
    context = {}
    if request.method == 'POST':
        form = PositionForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
        else:
            context['form'] = form
            return render(request, 'createposition.html', context)
    else:
        context['form'] = PositionForm()
        return render(request, 'createposition.html', context)


def update(request, candidate_id):
    if request.method == 'POST':
        post = Candidate.objects.get(id=candidate_id)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return index(request)
    else:
        post = Candidate.objects.get(id=candidate_id)
        context = {}
        context['form'] = PostForm(instance=post)
        return render(request, 'update.html', context)

votes/templates/base.html
{% load static %}
<html>
  <head>
    <title>
        {% block head %}
        this is the title head
        {% endblock %}
      </title>
      <link rel= "stylesheet" type="text/css" href="{% static 'votes/materialize/css/materialize.min.css' %}">
      {% block styles %}
      {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
        <script src="{% static 'votes/materialize/js/materialize.min.js' %}"> </script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

votes/templates/comment.html
{% extends 'base.html' %}
{% block head %}
this is the create page
{% endblock %}

{% block body %}
<form action="{% url 'post:comment' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
  {{ field.label}} {{field}}
  {{field.errors}}
    {% endfor %}
  <input type="submit" value ="Create">
</form>

{% endblock %}

votes/templates/create.html
{% extends 'base.html' %}
{% block head %}
this is the create page
{% endblock %}

{% block body %}
<form action="{% url 'votes:create' %}" method="POST">
  {% csrf_token %}
  <center> {% for field in form %}
  {{ field.label}} <br> {{field}}   <br>
  {{field.errors}}
    {% endfor %}

  <input type="submit" value ="Create">
</form>

{% endblock %}

votes/templates/createposition.html
{% extends 'base.html' %}
{% block head %}
this is the create page
{% endblock %}

{% block body %}
<form action="{% url 'votes:createposition' %}" method="POST">
  {% csrf_token %}
  <center>{% for field in form %}
  {{ field.label}} <br>{{field}}<br>
  {{field.errors}}
    {% endfor %}
    <input type="submit" value ="Create">
</form>

{% endblock %}

votes/templates/detail.html
{% extends 'base.html' %}
{% block head %}
  this is the detail page
{% endblock %}

{% block body %}
  <div align='center' class='container'>
  <div align='center' class='container'>
    <h1> Name: {{votes.firstname}}  {{votes.lastname}} </h1>
    <h4> Position: {{votes.position}} </h4>
    Platform: {{votes.platform}} <br/>
    Number of Votes: <input type="text"  id="demo" value="0"> </p>
    <br/>
    <hr>
  <a href ="{% url 'votes:index' %}"> Index </a>  ||
  <a href ="{% url 'votes:update' votes.id %}"> Update </a> ||
<button onclick='add()'> Vote </button>

<script>
var i=0;
function add(){
  document.getElementById("demo").value=++i;
}
</script>


  </div>
{% endblock %}

votes/templates/index.html
{% extends 'base.html' %}
{% block head %}
  this is the index page
{% endblock %}

{% block body %}
<div class ='container'>
<ol>
  {% for votes in candidate_names %}
 <div class="card-panel indigo lighten-4">
     <center>{{votes.lastname}},{{votes.firstname}} <br> Position: {{votes.position}} <center> <a href ="{% url 'votes:detail' votes.id %}"> Details </a> </div><br>
  {% endfor %}
</ol> </div>
<center>   <a href ="{% url 'votes:create' %}"> Create a new candidate</a> ||
 <a href ="{% url 'votes:createposition' %}"> Create a new position</a>

{% endblock %}

votes/templates/update.html
{% extends 'base.html' %}
{% block head %}
  this is the update page
{% endblock %}

{% block body %}
<form action="{% url 'votes:update' form.instance.id %}" method="POST">
  {% csrf_token %}
  <div class='container'>
  <center> {% for field in form %}
  {{ field.label}} <br> {{field}} <br>
  {% endfor %}
  <br><br>
  <input type="submit" value ="Update"> </div>
</form>

{% endblock %}